### ISSUE TITLE
Allow using as a middleware

### ISSUE THREAD

**Issue by blimmer** [blimmer/node-ember-cli-deploy-redis#2]
In my applications, I need to do some post-processing with the resultant `index.html` so I originally wrote this library as a utility function. However, it's probably more common for people to simply want to serve up the `index.html` directly without modification. I would be nice if you could use this library as a middleware or a utility function.
### Outstanding Questions
- What's the best structure for this?  
  I'm thinking the main `index.js` would contain the middleware, and the logic to fetch an `index.html` would be in a peer file that could also be imported and used on its own (for my case where I need to post-process).
- How to handle success for more than just Express?  
  I only have experience with ExpressJS, is there a standard way to simply send a `200` and an html string as a result?
- How to handle failure (in general)?  
  What's the best way to handle a failure? It seems that handling errors will be handled in a number of different ways depending on the user. Should you set a callback when you `require` the library and use as a middleware?

Anything else I didn't think of? This is my first Node middleware, so please excuse my ignorance on some of these topics. If anyone has recommended reading on writing middleware, please pass it along!

**Comment by lukemelia** [comment]
I suspect a layered API would be best. Provide the core utility as you already have, then add an express.js middleware wrapper with documentation on using it in an express app, and allow other people to contribute middleware for other frameworks.
