### ISSUE TITLE
Throttle calls to redis.get

### ISSUE THREAD

**Issue by ronco** [blimmer/node-ember-cli-deploy-redis#4]
I'd prefer not to hit up redis on every request that comes into my node server.  Now that this utility is establishing it's own redis client any memoization around the calls to redis should be done inside this library.  Can we add a `ttl` parameter to the options hash, to allow for this?

**Comment by blimmer** [comment]
This is a great idea. We've used [memoize](https://github.com/medikoo/memoize) before to do this with node_redis, so I think we could use the same logic here.

I'll add the help wanted label for now in case someone has time to do this. If not, I will try to tackle this in the next week or so. I'll post here if I start working on this issue to prevent multiple implementations.
