### ISSUE TITLE
api inconsistency

### ISSUE THREAD

**Issue by knownasilya** [blimmer/node-ember-cli-deploy-redis#6]
When using fetch  in the readme, the `'myapp'` is before the options, but for the default examples it's after. Why the inconsistency?

**Comment by blimmer** [comment]
Sorry, having trouble identifying the two places you're referring to.

The [fetchIndex](https://github.com/blimmer/node-ember-cli-deploy-redis/blob/develop/fetch.js#L31) method takes the app name as the second parameter.

The express middleware ([described here](https://github.com/blimmer/node-ember-cli-deploy-redis#example)) has a different signature and is [defined here](https://github.com/blimmer/node-ember-cli-deploy-redis/blob/develop/index.js#L4).

**Comment by knownasilya** [comment]
Yeah those places, how come the `connectionInfo` and `appName` are swapped between the two?

**Comment by blimmer** [comment]
I'm open to changing that for consistency if you want to do a PR. Make sure you bump to `0.2.0` and note in the changelog that there's a breaking change.

**Comment by blimmer** [comment]
v0.2.0 is published to npm, thank you.
